### ISSUE TITLE
JOSS package review 

### ISSUE THREAD

**Issue by seabbs** [giabaio/BCEA#12]
It can be very reassuring for users to get package code (as well as methods etc.) peer reviewed. [JOSS](https://joss.theoj.org) is a good way of getting this done (I could have missed that you have already done this). 

We are talking about getting as many Excel users to switch too R as possible and I think making your excellent package look as official as possible would be great.

Linked to #6

**Comment by giabaio** [comment]
The books have both been peer reviewed before it was published (over and above the post-publication comments and reviews). I have a paper in Journal of Statistical Software (to appear) for `survHE`, but not one for `BCEA`. At this stage, I'm not sure another paper on the software would contribute much more, though, I think --- given the point above about the books... 

Closing this also, but as usual, happy to keep discussing.

**Comment by seabbs** [comment]
Fair enough. 

My point was that this would be a review of the code, not the methods or application. Unless I am wrong neither the review of the book or the paper will have looked at the code/documentation extensively? A JOSS review checks that code and docs meet community best practices.

In JOSS the paper is a half-page abstract -the review looks at the code.

Example [paper](https://joss.theoj.org/papers/10.21105/joss.01260) and [review](https://github.com/openjournals/joss-reviews/issues/1260).
