### ISSUE TITLE
Cost effectiveness for non-standard models

### ISSUE THREAD

**Issue by seabbs** [giabaio/BCEA#13]
In my group we have a lot of people working on dynamic infectious disease models and then running cost effectiveness. This means they are typically working with simulation output for model states that they then apply health utilities and costs to. 

Would you be interested in either some additional tooling or a simple vignette walking through how to take a model like this and use {BCEA} with it. 

Linked to #6

**Comment by giabaio** [comment]
Together with a former PhD student, we too have done some work on infectious diseases and cost-effectiveness analysis. See some links [here](http://www.statistica.it/gianluca/project/hpv/) (including relevant literature) and a talk I gave at Imperial earlier this year, [here](http://statistica.it/gianluca/Talks/BMM.pdf).

I think that **to some extent**, infectious disease analyses may be integrated within the standard paradigm for cost-effectiveness --- essentially, the point in our work was that you have a trade-off between the resolution in the dynamic model and the fitness for the purposes of the wider economic analysis. And stuff like the "expanded" framework of (Bayesian) Markov models, which approximate to a good degree (at least in the examples we've considered) the full continuous-time transmission models could be very well suited for cost-effectiveness analysis.

Having said that, there may be lots more to discuss and potentially more complex models to be constructed. We have used extensively `BCEA` in our work on infectious disease (and in our set up, it was just another analysis with more of the same). If you have specific cases where that would *not* be the case, then shout and we can discuss.

**Comment by seabbs** [comment]
Yes, I very much agree that the current package works well for this. You are correct that resolution can add an additional step but ultimately this seems fairly easy to resolve.

Essentially my point is that some more documentation - in the form of a vignette - would really help to make this clear.  Having a clear case study taking the output of an ID model and walking through the CE steps would be very useful to my group and I imagine others. This might help with the perception that `BCEA` is not model agnostic. 

Again happy to work on a pull request for this.

**Comment by giabaio** [comment]
OK. I'll close this now, then --- but with the understanding we're both on it! :-)
