### ISSUE TITLE
Expanded Travis testing grid

### ISSUE THREAD

**Issue by seabbs** [giabaio/BCEA#16]
It would be really great to have BCEA tested against multiple versions of R (release, devel, and older etc.) It would also be great to have testing against Linux, MacOS, and Windows (I might have missed this).

Linked to #6

**Comment by giabaio** [comment]
All my development is in Linux, so I do use tools such as Travis. BUT: see my response to your issue #8 --- if you have something more specific in mind, let me know!

**Comment by seabbs** [comment]
Great. 

So by this, I really meant testing against different Linux flavors, macOS, and Windows (which you are doing with Appveyor :smile:) and multiple versions of R. 

Travis can be configured to do this ([example](https://github.com/seabbs/getTBinR/blob/master/.travis.yml)) but as far as I can tell your current set-up is just running a single check on the release version of R. 

Are you happy for a pull request on this?

**Comment by giabaio** [comment]
Sure.
