### ISSUE TITLE
error not clear when providing data.frames instead of matrices 

### ISSUE THREAD

**Issue by David-rios** [giabaio/BCEA#31]
Hi! 
Pretty minor but error message when providing data frames instead of matrices to bcea could be clearer. Reproducible example below 

``` r

library(BCEA)
c1 <- data.frame(c1 = runif(100),
                 c2 = runif(100) )

e1 <-data.frame(c1 = runif(100),
                c2 = runif(100))

m <-bcea(c = as.matrix(c1) ,e =  as.matrix(e1) ,interventions = c("Intervention", "SoC"),Kmax = 60,ref = 1)
class(m)
#> [1] "bcea"
m <-bcea(c = c1 ,e =  e1 ,interventions = c("Intervention", "SoC"),Kmax = 60,ref = 1)
#> Error in rep(e, K) * rep(k, each = n.sim * n.comparators): non-numeric argument to binary operator
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by giabaio** [comment]
The `dev` version of BCEA, available from GitHub and soon to be submitted to CRAN does clarify the error. If you test the code on the 2.4.1 version, you get
```
> m <-bcea(c = c1 ,e =  e1 ,interventions = c("Intervention", "SoC"),Kmax = 60,ref = 1)
Error: eff and cost must be matrices.
```
We may decide to convert anything that isn't a matrix on the fly to even avoid this...
