### ISSUE TITLE
make.report(...) function expects an Rmd file in /report.Rmd location?

### ISSUE THREAD

**Issue by jSoboil** [giabaio/BCEA#43]
R returns the following error when trying to knit an automated report using BCEA:

`Error in abs_path(input) : The file '/report.Rmd' does not exist.`

**Comment by giabaio** [comment]
Can you elaborate, possibly with a reproducible example? I'll look into it then!

Thanks for this!
G

**Comment by jSoboil** [comment]
Hey Gianluca,

It initially produced the error with a large model, but after running a simple script it reproduces it. See below:
`# Set seed:
set.seed(13412)

# Load libraries
library(BCEA)

# Randomly sample effects and cost data:
eff <- matrix(data = (rnorm(n = 2 * 100)), nrow = 100, ncol = 2)
cost <- matrix(data = (rlnorm(n = 2 * 100, meanlog = 5)), nrow = 100, ncol = 2)

# Create BCEA object
df_cea <- bcea(eff = eff, cost = cost, ref = 1, .comparison = 2)

# Call make.report() function:
BCEA::make.report(bcea(eff = eff, cost = cost, ref = 1, .comparison = 2))
`

**Comment by giabaio** [comment]
Hi @jSoboil,
Sorry for being a bit slow. I *think* this is sorted. If you install the current `dev' version, with
```
remotes::install_github("giabaio/BCEA",ref="dev")
```
all should be back to working OK. 

Please do shout if there's still something not quite right!

**Comment by jSoboil** [comment]
Thanks, Gianluca! Not slow at all...
