### ISSUE TITLE
[QUESTION] Any papers that have used {BCEA}?

### ISSUE THREAD

**Issue by serkor1** [giabaio/BCEA#64]
Hi,

Firstly, what an amazing package. Based on the documentation and your paper in The R Journal, this package is everything that I am looking for.

We are a group of research planning to do a Cost-Effectiveness Analysis on a randomized control trial, and are planning to use this package.

Can you guide me to any CEA papers that (maybe) follow the CHEERS guidelines whom used this paper, which might also be reproducable? 

Best,

Serkan

**Comment by giabaio** [comment]
Thanks for this, @serkor1!

So: there's quite some literature on `BCEA`: I think the best places to look for references are
- [https://gianluca.statistica.it/software/bcea/](https://gianluca.statistica.it/software/bcea/) (where you can find some other references (from our work)
- If you look into Google Scholar (e.g. [here](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=BCEA+cost-effectiveness&btnG=), but you can change the search and replace `cost-effectiveness` for `health economics` or something...) there are a bunch more...

Hope this helps!
